---
- name: Default conversion_inhibited to false
  ansible.builtin.set_fact:
    conversion_inhibited: false

- name: Collect human readable report results
  ansible.builtin.slurp:
    src: "{{ parse_c2r_report_result_filename_txt }}"
  register: results_txt

- name: Collect JSON report results
  ansible.builtin.slurp:
    src: "{{ parse_c2r_report_result_filename_json }}"
  register: results_json

- name: Parse report results
  ansible.builtin.set_fact:
    convert2rhel_report_txt: "{{ results_txt.content | b64decode | split('\n') }}"
    convert2rhel_report_json: "{{ results_json.content | b64decode | from_json }}"

- name: Check for inhibitor statuses in the report
  ansible.builtin.set_fact:
    conversion_inhibited: true
  when:
    - item in inhibitors_statuses
  loop: "{{ report_message_levels.values() | unique }}"
  vars:
    # All of these are unnaceptable based on https://github.com/oamg/convert2rhel-worker-scripts/blob/main/scripts/preconversion_assessment_script.py#L121
    inhibitors_statuses:
      - "SKIP"
      - "OVERRIDABLE"
      - "ERROR"
    report_message_levels: "{{ lookup('ansible.utils.to_paths', convert2rhel_report_json) | dict2items | selectattr('key', 'search', 'level') | items2dict }}"
...
