---
# This workflow action will run ansible-lint, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write
  pull-requests: write

jobs:
  ansible-lint:
    uses: redhat-cop/infra.convert2rhel/.github/workflows/ansible-lint.yml@main
  sanity:
    uses: redhat-cop/infra.convert2rhel/.github/workflows/ansible-test.yml@main
  prechecks:
    needs:
      - ansible-lint
      - sanity
    runs-on: ubuntu-latest
    if: always() && github.repository == 'redhat-cop/infra.convert2rhel'
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.ansible-lint.result }}',
          '${{ needs.sanity.result }}',
          ]) == {'success'}"
  infra_release:
    needs:
      - prechecks
    runs-on: ubuntu-latest
    if: always() && github.repository == 'redhat-cop/infra.convert2rhel'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install --upgrade ansible-core

      - name: Update version in galaxy.yml
        run: sed -i 's/version:.*$/version:{{:dumb_space_issue:}}${{ github.ref_name }}/' galaxy.yml; sed -i 's/{{:dumb_space_issue:}}/ /' galaxy.yml

      - name: Build collection
        run: ansible-galaxy collection build -vvv
        shell: bash
        working-directory: ${{ vars.GITHUB_PATH }}

      - name: Get tar name
        run: echo "tar_file=$(ls | grep '.tar')" >> $GITHUB_OUTPUT
        id: build

      - name: Get version
        run: echo "NUM=$(cat galaxy.yml | grep version | head -1 | cut -d ':' -f 2 | awk '{print $1}')" >> $GITHUB_OUTPUT
        id: vers

      - name: Install collection
        run: ansible-galaxy collection install ./infra-convert2rhel-${{ steps.vers.outputs.NUM }}.tar.gz -p /home/runner/collections
        shell: bash
        working-directory: ${{ vars.GITHUB_PATH }}

      - name: Publish to galaxy
        run: ansible-galaxy collection publish --api-key=${{ secrets.GALAXY_INFRA_KEY }} ${{ steps.build.outputs.tar_file }}

      - name: Publish to Automation Hub
        run: |
          cat << EOF > ansible.cfg
          [galaxy]
          server_list = rh_automation_hub

          [galaxy_server.rh_automation_hub]
          url=https://cloud.redhat.com/api/automation-hub/
          auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          token=${{ secrets.CONSOLE_API_KEY }}
          EOF
          ansible-galaxy collection publish ${{ steps.build.outputs.tar_file }}
          rm ansible.cfg

      - name: Upload files to tag
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.build.outputs.tar_file }}
          tag: ${{ github.ref }}
          overwrite: true
  changelog:
    needs:
      - infra_release
    runs-on: ubuntu-latest
    if: always() && github.repository == 'redhat-cop/infra.convert2rhel'
    env:
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install --upgrade ansible-core antsibull-changelog

      - name: Update version in galaxy.yml
        run: sed -i 's/version:.*$/version:{{:dumb_space_issue:}}${{ github.ref_name }}/' galaxy.yml; sed -i 's/{{:dumb_space_issue:}}/ /' galaxy.yml

      - name: Run changelog
        run: antsibull-changelog release --verbose --version ${{ github.ref_name }}

      - name: Create Pull Request
        id: prcreate
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update changelog ${{ github.ref_name }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: main
          branch: changelog-patches
          delete-branch: true
          title: '[RELEASE] Update changelog ${{ github.ref_name }}'
          body: |
            Update changelog
            - Updated with changelog for release ${{ github.ref_name }}
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            changelog
            automated pr
          draft: false
...
